### ISSUE TITLE
Can't build cross native (windows) gem.

### ISSUE THREAD

**Issue by naitoh** [ruby-numo/numo-narray#101]
## No problem case (Numo::NArray 0.9.0.4 ... d8e1e9e66d871c777c34be30d6442c6193613fac)

```
$ pwd
/home/naitoh/test/
$ git clone https://github.com/ruby-numo/numo-narray.git
$ cd numo-narray
$ git checkout d8e1e9e66d871c777c34be30d6442c6193613fac
```

```
$ vi numo-narray.gemspec 
```

* before: spec.add_development_dependency 'rake-compiler', "~> 1.0", ">= 1.0.1"
* changed:  spec.add_development_dependency 'rake-compiler', "1.0.2"

rake-compiler 1.0.3 has problem, need to use 1.0.2.

```
$ vi Rakefile 
```

* before: cross_platforms = ["x86-mingw32", "x64-mingw32"]
* changed:  cross_platforms = ["x86_64-linux"]

I will change it for confirmation of cross-compilation tentatively.
___(I'm sorry, this step was missing so I added it.)___

```
$ git clone file:///home/naitoh/test/numo-narray/tmp/windows/.git tmp/windows 
Cloning into 'tmp/windows'...
warning: You appear to have cloned an empty repository.
$ cd tmp/windows      
$ bundle
Resolving dependencies...
Using rake 0.9.6
Using bundler 1.7.9
Using diff-lcs 1.3
Using numo-narray 0.9.0.4 from source at .
Using rake-compiler 1.0.2
Using rake-compiler-dock 0.6.3
Using rspec-support 3.7.1
Using rspec-core 3.7.1
Using rspec-expectations 3.7.0
Using rspec-mocks 3.7.0
Using rspec 3.7.0
Your bundle is complete!
Use `bundle show [gemname]` to see where a bundled gem is installed.
$ rake cross native gem

(snip)

cp tmp/x86_64-linux/numo/narray/2.2.0/numo/narray.so tmp/x86_64-linux/stage/lib/numo/narray.so
cd pkg/numo-narray-0.9.0.4-x86_64-linux
  Successfully built RubyGem
  Name: numo-narray
  Version: 0.9.0.4
  File: numo-narray-0.9.0.4-x86_64-linux.gem
mv numo-narray-0.9.0.4-x86_64-linux.gem ..
cd -
```

Cross native (Windows) gem build successed. 

## Problem case (Numo::NArray 95d04b5ef3c75ce8acf41e6934806bf50b6ffc23 ... 0.9.0.5 ... master )

```
$ cd ../..
$ rm -rf pkg/
$ rm -rf tmp/
$ rm numo-narray.gemspec
$ git checkout numo-narray.gemspec
$ git checkout master
```

```
$ vi numo-narray.gemspec 
```

* before: spec.add_development_dependency 'rake-compiler', "~> 1.0", ">= 1.0.1"
* changed:  spec.add_development_dependency 'rake-compiler', "1.0.2"

```
$ git clone file:///home/naitoh/test/numo-narray/tmp/windows/.git tmp/windows 
Cloning into 'tmp/windows'...
warning: You appear to have cloned an empty repository.
$ cd tmp/windows      
$ bundle
Resolving dependencies...
Using rake 0.9.6
Using bundler 1.7.9
Using numo-narray 0.9.1.2 (was 0.9.0.4) from source at .
Using power_assert 1.1.1
Using rake-compiler 1.0.2
Using rake-compiler-dock 0.6.3
Using test-unit 3.2.8
Your bundle is complete!
Use `bundle show [gemname]` to see where a bundled gem is installed.
$ rake cross native gem
(in /home/naitoh/test/numo-narray)
mkdir -p tmp/x86_64-linux/numo/narray/2.2.0/numo
cd tmp/x86_64-linux/numo/narray/2.2.0
/home/naitoh/.rvm/rubies/ruby-2.2.0/bin/ruby -I. ../../../../../ext/numo/narray/extconf.rb
checking for stdbool.h... yes
checking for stdint.h... yes
checking for bool in stdbool.h... yes
checking for u_int8_t in stdint.h... yes
checking for u_int16_t in stdint.h... yes
checking for int32_t in stdint.h... yes
checking for u_int32_t in stdint.h... yes
checking for int64_t in stdint.h... yes
checking for u_int64_t in stdint.h... yes
checking for exp10()... yes
checking for rb_cComplex... yes
creating numo/extconf.h
creating Makefile
cd -
cd tmp/x86_64-linux/numo/narray/2.2.0
/usr/bin/gmake
compiling ../../../../../ext/numo/narray/narray.c
compiling ../../../../../ext/numo/narray/array.c
compiling ../../../../../ext/numo/narray/step.c
compiling ../../../../../ext/numo/narray/index.c
compiling ../../../../../ext/numo/narray/ndloop.c
compiling ../../../../../ext/numo/narray/data.c
compiling ../../../../../ext/numo/narray/math.c
compiling ../../../../../ext/numo/narray/SFMT.c
compiling ../../../../../ext/numo/narray/struct.c
compiling ../../../../../ext/numo/narray/rand.c
linking shared-object numo/narray.so
gcc: error: types/bit.o: No such file or directory
gcc: error: types/int8.o: No such file or directory
gcc: error: types/int16.o: No such file or directory
gcc: error: types/int32.o: No such file or directory
gcc: error: types/int64.o: No such file or directory
gcc: error: types/uint8.o: No such file or directory
gcc: error: types/uint16.o: No such file or directory
gcc: error: types/uint32.o: No such file or directory
gcc: error: types/uint64.o: No such file or directory
gcc: error: types/sfloat.o: No such file or directory
gcc: error: types/dfloat.o: No such file or directory
gcc: error: types/scomplex.o: No such file or directory
gcc: error: types/dcomplex.o: No such file or directory
gcc: error: types/robject.o: No such file or directory
gmake: *** [narray.so] Error 1
rake aborted!
Command failed with status (2): [/usr/bin/gmake...]
/home/naitoh/.rvm/gems/ruby-2.2.0/gems/rake-compiler-1.0.2/lib/rake/extensiontask.rb:165:in `block (2 levels) in define_compile_tasks'
/home/naitoh/.rvm/gems/ruby-2.2.0/gems/rake-compiler-1.0.2/lib/rake/extensiontask.rb:164:in `block in define_compile_tasks'
Tasks: TOP => native => native:x86_64-linux => native:numo-narray:x86_64-linux => tmp/x86_64-linux/stage/lib/numo/narray.so => copy:numo/narray:x86_64-linux:2.2.0 => tmp/x86_64-linux/numo/narray/2.2.0/numo/narray.so
(See full trace by running task with --trace)
```
cross native (Windows) gem build failed. 

Since 95d04b5ef3c75ce8acf41e6934806bf50b6ffc23, cross native (Windows) build is not possible.

# Environment
* CentOS Linux release 7.3.1611 (Core) 
* ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-linux]

**Comment by naitoh** [comment]
I have created a patch that can build for windows, so I sent a pull request #106.
Thank you for the merge.

Best regards.
