### ISSUE TITLE
Masking of 3D matrix by wrong shapes. (third axis)

### ISSUE THREAD

**Issue by kojix2** [ruby-numo/numo-narray#118]
Hello. 
Crash report.

Sample 1
```ruby
require 'numo/narray'

a = Numo::UInt8.new(2,2,2).seq
b = Numo::UInt8.new(2,2,1).seq

a[b > 0] 
```
```terminal
free(): invalid next size (fast)
中止 (コアダンプ)
```
Sample 2
```ruby
require 'numo/narray'

a = Numo::UInt8.new(2,2,3).seq
b = Numo::UInt8.new(2,2,1).seq

a[b > 0] 
```
```terminal
malloc(): memory corruption
中止 (コアダンプ)
```
Sample 3
```ruby
require 'numo/narray'

a = Numo::UInt8.new(2,2,2,2).seq
b = Numo::UInt8.new(2,2,2,1).seq

a[b > 0]
```
```terminal
free(): invalid next size (fast)
中止 (コアダンプ)
```
Sample 4
```ruby
require 'numo/narray'

a = Numo::UInt8.new(2,2,2,2).seq
b = Numo::UInt8.new(2,2,1,1).seq

a[b > 0]
```
```terminal
munmap_chunk(): invalid pointer
中止 (コアダンプ)
```
Sample 5
```ruby
require 'numo/narray'

a = Numo::UInt8.new(10,10,3).seq
b = Numo::UInt8.new(10,10,1).seq

p a[b > 0] 
```

```terminal
hoge.rb:6: [BUG] Segmentation fault at 0x0000000000000078
ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-linux]

-- Control frame information -----------------------------------------------
c:0003 p:---- s:0013 e:000012 CFUNC  :p
c:0002 p:0067 s:0008 E:001280 EVAL   hoge.rb:6 [FINISH]
c:0001 p:0000 s:0003 E:000780 (none) [FINISH]

-- Ruby level backtrace information ----------------------------------------
hoge.rb:6:in `<main>'
hoge.rb:6:in `p'

-- Machine register context ------------------------------------------------
 RIP: 0x00007f750775b9bb RBP: 0x0000000000000007 RSP: 0x00007ffd20b8c6f0
 RAX: 0x0000561eefa75460 RBX: 0x0000561eef587038 RCX: 0x0000000000000000
 RDX: 0x0000000000000000 RDI: 0x0000000000000000 RSI: 0x0000000000000068
  R8: 0x0000561eef587010  R9: 0x0000000000000000 R10: 0x0000000000000000
 R11: 0x00007f75078acca0 R12: 0x0000000000000005 R13: 0x00007f75078acc40
 R14: 0x0000000000000070 R15: 0x0000000000000060 EFL: 0x0000000000010283

-- C level backtrace information -------------------------------------------
```
I like NArray. 
Thank you.

**Comment by kojix2** [comment]
* latest NArray (github master)
* Ruby 2.5.3
* Ubuntu 18.10

**Comment by masa16** [comment]
Added checking exactly same shape.
https://github.com/ruby-numo/numo-narray/commit/795a5f80ed65ea1f8c116f809a490f63dda42300

**Comment by kojix2** [comment]
I confirmed.
 Thank you !
