### ISSUE TITLE
Segmentation fault with cast on Windows

### ISSUE THREAD

**Issue by ankane** [ruby-numo/numo-narray#156]
Hi, I'm running into a segmentation fault with `cast` on Windows. It doesn't occur when garbage collection is disabled. Here's a minimal script to reproduce:

```ruby
require "numo/narray"

data = 3000.times.map { |v| 1000000000 + 86400 * v }

10000.times do |i|
  puts i
  p Numo::DFloat.cast(data.map { |v| v + 1 })
end
```

It happens with Ruby version 2.6.3 on AppVeyor: https://ci.appveyor.com/project/ankane/numo-repro/builds/32090203.

Here's the trace:

```txt
repro.rb:7: [BUG] Segmentation fault
ruby 2.6.3p62 (2019-04-16 revision 67580) [x64-mingw32]
-- Control frame information -----------------------------------------------
c:0006 p:---- s:0024 e:000023 CFUNC  :<=
c:0005 p:---- s:0021 e:000020 CFUNC  :cast
c:0004 p:0028 s:0016 e:000014 BLOCK  repro.rb:7 [FINISH]
c:0003 p:---- s:0011 e:000010 CFUNC  :times
c:0002 p:0025 s:0007 E:001128 EVAL   repro.rb:5 [FINISH]
c:0001 p:0000 s:0003 E:000150 (none) [FINISH]
-- Ruby level backtrace information ----------------------------------------
repro.rb:5:in `<main>'
repro.rb:5:in `times'
repro.rb:7:in `block in <main>'
repro.rb:7:in `cast'
repro.rb:7:in `<='
-- C level backtrace information -------------------------------------------
C:\windows\SYSTEM32\ntdll.dll(ZwWaitForSingleObject+0xa) [0x00007ffc5190079a]
C:\windows\system32\KERNELBASE.dll(WaitForSingleObjectEx+0x98) [0x00007ffc4ede1118]
C:\Ruby26-x64\bin\x64-msvcrt-ruby260.dll(rb_vm_bugreport+0x2e1) [0x000000006a6510f1]
C:\Ruby26-x64\bin\x64-msvcrt-ruby260.dll(rb_bug_context+0x6d) [0x000000006a4c53dd]
C:\Ruby26-x64\bin\x64-msvcrt-ruby260.dll(rb_check_safe_obj+0x4d0) [0x000000006a5c57a0]
 [0x000000000040234c]
C:\windows\SYSTEM32\ntdll.dll(_C_specific_handler+0x96) [0x00007ffc518f1e26]
C:\windows\SYSTEM32\ntdll.dll(_chkstk+0x9d) [0x00007ffc5190349d]
C:\windows\SYSTEM32\ntdll.dll(RtlRaiseException+0xf67) [0x00007ffc518c48d7]
C:\windows\SYSTEM32\ntdll.dll(KiUserExceptionDispatcher+0x3a) [0x00007ffc5190262a]
C:\Ruby26-x64\bin\x64-msvcrt-ruby260.dll(rb_id_table_lookup+0x0) [0x000000006a5fc9a0]
C:\Ruby26-x64\bin\x64-msvcrt-ruby260.dll(rb_f_notimplement+0x170f) [0x000000006a6301af]
C:\Ruby26-x64\bin\x64-msvcrt-ruby260.dll(rb_vm_call+0x8f) [0x000000006a63eadf]
C:\Ruby26-x64\bin\x64-msvcrt-ruby260.dll(rb_check_funcall_default+0x76) [0x000000006a6436e6]
C:\Ruby26-x64\bin\x64-msvcrt-ruby260.dll(rb_check_funcall+0x12) [0x000000006a6438c2]
C:\Ruby26-x64\bin\x64-msvcrt-ruby260.dll(rb_num_coerce_relop+0x2f) [0x000000006a53f03f]
C:\Ruby26-x64\bin\x64-msvcrt-ruby260.dll(rb_f_eval+0x50f) [0x000000006a63e63f]
C:\Ruby26-x64\bin\x64-msvcrt-ruby260.dll(rb_vm_call+0x983) [0x000000006a63f3d3]
C:\Ruby26-x64\bin\x64-msvcrt-ruby260.dll(rb_funcallv+0x36) [0x000000006a63f926]
C:\projects\numo-repro\vendor\bundle\ruby\2.6.0\gems\numo-narray-0.9.1.6\lib\numo\narray.so(Init_narray+0xd8d) [0x0000000068b8666d]
C:\projects\numo-repro\vendor\bundle\ruby\2.6.0\gems\numo-narray-0.9.1.6\lib\numo\narray.so(Init_narray+0xeab) [0x0000000068b8678b]
C:\projects\numo-repro\vendor\bundle\ruby\2.6.0\gems\numo-narray-0.9.1.6\lib\numo\narray.so(Init_narray+0x1103) [0x0000000068b869e3]
C:\projects\numo-repro\vendor\bundle\ruby\2.6.0\gems\numo-narray-0.9.1.6\lib\numo\narray.so(Init_narray+0x130e) [0x0000000068b86bee]
C:\projects\numo-repro\vendor\bundle\ruby\2.6.0\gems\numo-narray-0.9.1.6\lib\numo\narray.so(nary_s_new_like+0x59) [0x0000000068b87099]
C:\projects\numo-repro\vendor\bundle\ruby\2.6.0\gems\numo-narray-0.9.1.6\lib\numo\narray.so(Init_numo_sfloat+0x125f4) [0x0000000068c49964]
C:\Ruby26-x64\bin\x64-msvcrt-ruby260.dll(rb_error_arity+0x136) [0x000000006a6338d6]
C:\Ruby26-x64\bin\x64-msvcrt-ruby260.dll(rb_check_funcall+0x1bc) [0x000000006a643a6c]
C:\Ruby26-x64\bin\x64-msvcrt-ruby260.dll(rb_vm_exec+0xf2) [0x000000006a63bab2]
C:\Ruby26-x64\bin\x64-msvcrt-ruby260.dll(rb_yield_1+0x24f) [0x000000006a649b9f]
C:\Ruby26-x64\bin\x64-msvcrt-ruby260.dll(rb_int_abs+0x461) [0x000000006a538331]
C:\Ruby26-x64\bin\x64-msvcrt-ruby260.dll(rb_error_arity+0x136) [0x000000006a6338d6]
C:\Ruby26-x64\bin\x64-msvcrt-ruby260.dll(rb_vm_invoke_bmethod+0x48e) [0x000000006a63cd3e]
C:\Ruby26-x64\bin\x64-msvcrt-ruby260.dll(rb_vm_invoke_bmethod+0xb83) [0x000000006a63d433]
C:\Ruby26-x64\bin\x64-msvcrt-ruby260.dll(rb_check_funcall+0x14ef) [0x000000006a644d9f]
C:\Ruby26-x64\bin\x64-msvcrt-ruby260.dll(rb_vm_exec+0xf2) [0x000000006a63bab2]
C:\Ruby26-x64\bin\x64-msvcrt-ruby260.dll(rb_call_end_proc+0x15c) [0x000000006a4c92fc]
C:\Ruby26-x64\bin\x64-msvcrt-ruby260.dll(ruby_run_node+0x59) [0x000000006a4cd6a9]
 [0x0000000000402d87]
 [0x00000000004013a5]
 [0x000000000040150b]
C:\windows\system32\KERNEL32.DLL(BaseThreadInitThunk+0x22) [0x00007ffc4ef013d2]
-- Other runtime information -----------------------------------------------
* Loaded script: repro.rb
* Loaded features:
    0 enumerator.so
    1 thread.rb
    2 rational.so
    3 complex.so
    4 C:/Ruby26-x64/lib/ruby/2.6.0/x64-mingw32/enc/encdb.so
    5 C:/Ruby26-x64/lib/ruby/2.6.0/x64-mingw32/enc/trans/transdb.so
    6 C:/Ruby26-x64/lib/ruby/2.6.0/x64-mingw32/enc/windows_1252.so
    7 C:/Ruby26-x64/lib/ruby/2.6.0/x64-mingw32/rbconfig.rb
    8 C:/Ruby26-x64/lib/ruby/site_ruby/2.6.0/rubygems/compatibility.rb
    9 C:/Ruby26-x64/lib/ruby/site_ruby/2.6.0/rubygems/defaults.rb
   10 C:/Ruby26-x64/lib/ruby/site_ruby/2.6.0/rubygems/deprecate.rb
   11 C:/Ruby26-x64/lib/ruby/site_ruby/2.6.0/rubygems/errors.rb
   12 C:/Ruby26-x64/lib/ruby/site_ruby/2.6.0/rubygems/path_support.rb
   13 C:/Ruby26-x64/lib/ruby/site_ruby/2.6.0/rubygems/version.rb
   14 C:/Ruby26-x64/lib/ruby/site_ruby/2.6.0/rubygems/requirement.rb
   15 C:/Ruby26-x64/lib/ruby/site_ruby/2.6.0/rubygems/platform.rb
   16 C:/Ruby26-x64/lib/ruby/site_ruby/2.6.0/rubygems/basic_specification.rb
   17 C:/Ruby26-x64/lib/ruby/site_ruby/2.6.0/rubygems/stub_specification.rb
   18 C:/Ruby26-x64/lib/ruby/2.6.0/delegate.rb
   19 C:/Ruby26-x64/lib/ruby/2.6.0/uri/rfc2396_parser.rb
   20 C:/Ruby26-x64/lib/ruby/2.6.0/uri/rfc3986_parser.rb
   21 C:/Ruby26-x64/lib/ruby/2.6.0/uri/common.rb
   22 C:/Ruby26-x64/lib/ruby/2.6.0/uri/generic.rb
   23 C:/Ruby26-x64/lib/ruby/2.6.0/uri/file.rb
   24 C:/Ruby26-x64/lib/ruby/2.6.0/uri/ftp.rb
   25 C:/Ruby26-x64/lib/ruby/2.6.0/uri/http.rb
   26 C:/Ruby26-x64/lib/ruby/2.6.0/uri/https.rb
   27 C:/Ruby26-x64/lib/ruby/2.6.0/uri/ldap.rb
   28 C:/Ruby26-x64/lib/ruby/2.6.0/uri/ldaps.rb
   29 C:/Ruby26-x64/lib/ruby/2.6.0/uri/mailto.rb
   30 C:/Ruby26-x64/lib/ruby/2.6.0/uri.rb
   31 C:/Ruby26-x64/lib/ruby/site_ruby/2.6.0/rubygems/specification_policy.rb
   32 C:/Ruby26-x64/lib/ruby/site_ruby/2.6.0/rubygems/util/list.rb
   33 C:/Ruby26-x64/lib/ruby/2.6.0/x64-mingw32/stringio.so
   34 C:/Ruby26-x64/lib/ruby/site_ruby/2.6.0/rubygems/specification.rb
   35 C:/Ruby26-x64/lib/ruby/site_ruby/2.6.0/rubygems/exceptions.rb
   36 C:/Ruby26-x64/lib/ruby/site_ruby/2.6.0/ruby_installer/runtime/singleton.rb
   37 C:/Ruby26-x64/lib/ruby/site_ruby/2.6.0/ruby_installer/runtime.rb
   38 C:/Ruby26-x64/lib/ruby/site_ruby/2.6.0/ruby_installer/runtime/msys2_installation.rb
   39 C:/Ruby26-x64/lib/ruby/2.6.0/x64-mingw32/fiddle.so
   40 C:/Ruby26-x64/lib/ruby/2.6.0/fiddle/function.rb
   41 C:/Ruby26-x64/lib/ruby/2.6.0/fiddle/closure.rb
   42 C:/Ruby26-x64/lib/ruby/2.6.0/fiddle.rb
   43 C:/Ruby26-x64/lib/ruby/site_ruby/2.6.0/ruby_installer/runtime/dll_directory.rb
   44 C:/Ruby26-x64/lib/ruby/2.6.0/x64-mingw32/enc/utf_16le.so
   45 C:/Ruby26-x64/lib/ruby/2.6.0/x64-mingw32/enc/trans/utf_16_32.so
   46 C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/defaults/operating_system.rb
   47 C:/Ruby26-x64/lib/ruby/site_ruby/2.6.0/rubygems/util.rb
   48 C:/Ruby26-x64/lib/ruby/site_ruby/2.6.0/rubygems/bundler_version_finder.rb
   49 C:/Ruby26-x64/lib/ruby/site_ruby/2.6.0/rubygems/dependency.rb
   50 C:/Ruby26-x64/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_gem.rb
   51 C:/Ruby26-x64/lib/ruby/2.6.0/monitor.rb
   52 C:/Ruby26-x64/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb
   53 C:/Ruby26-x64/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_warn.rb
   54 C:/Ruby26-x64/lib/ruby/site_ruby/2.6.0/rubygems.rb
   55 C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/did_you_mean-1.3.0/lib/did_you_mean/version.rb
   56 C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/did_you_mean-1.3.0/lib/did_you_mean/core_ext/name_error.rb
   57 C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/did_you_mean-1.3.0/lib/did_you_mean/levenshtein.rb
   58 C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/did_you_mean-1.3.0/lib/did_you_mean/jaro_winkler.rb
   59 C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/did_you_mean-1.3.0/lib/did_you_mean/spell_checker.rb
   60 C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/did_you_mean-1.3.0/lib/did_you_mean/spell_checkers/name_error_checkers/class_name_checker.rb
   61 C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/did_you_mean-1.3.0/lib/did_you_mean/spell_checkers/name_error_checkers/variable_name_checker.rb
   62 C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/did_you_mean-1.3.0/lib/did_you_mean/spell_checkers/name_error_checkers.rb
   63 C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/did_you_mean-1.3.0/lib/did_you_mean/spell_checkers/method_name_checker.rb
   64 C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/did_you_mean-1.3.0/lib/did_you_mean/spell_checkers/key_error_checker.rb
   65 C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/did_you_mean-1.3.0/lib/did_you_mean/spell_checkers/null_checker.rb
   66 C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/did_you_mean-1.3.0/lib/did_you_mean/formatters/plain_formatter.rb
   67 C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/did_you_mean-1.3.0/lib/did_you_mean.rb
   68 C:/Ruby26-x64/lib/ruby/2.6.0/x64-mingw32/enc/trans/single_byte.so
   69 C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/version.rb
   70 C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/compatibility_guard.rb
   71 C:/Ruby26-x64/lib/ruby/2.6.0/x64-mingw32/pathname.so
   72 C:/Ruby26-x64/lib/ruby/2.6.0/pathname.rb
   73 C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/constants.rb
   74 C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/rubygems_integration.rb
   75 C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/current_ruby.rb
   76 C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/shared_helpers.rb
   77 C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/vendor/fileutils/lib/fileutils/version.rb
   78 C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/vendor/fileutils/lib/fileutils.rb
   79 C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/vendored_fileutils.rb
   80 C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/errors.rb
   81 C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/environment_preserver.rb
   82 C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/plugin/api.rb
   83 C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/plugin.rb
   84 C:/Ruby26-x64/lib/ruby/site_ruby/2.6.0/rubygems/source/git.rb
   85 C:/Ruby26-x64/lib/ruby/site_ruby/2.6.0/rubygems/source/installed.rb
   86 C:/Ruby26-x64/lib/ruby/site_ruby/2.6.0/rubygems/source/specific_file.rb
   87 C:/Ruby26-x64/lib/ruby/site_ruby/2.6.0/rubygems/source/local.rb
   88 C:/Ruby26-x64/lib/ruby/site_ruby/2.6.0/rubygems/source/lock.rb
   89 C:/Ruby26-x64/lib/ruby/site_ruby/2.6.0/rubygems/source/vendor.rb
   90 C:/Ruby26-x64/lib/ruby/site_ruby/2.6.0/rubygems/source.rb
   91 C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/gem_helpers.rb
   92 C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/match_platform.rb
   93 C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/rubygems_ext.rb
   94 C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/build_metadata.rb
   95 C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler.rb
   96 C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/settings.rb
   97 C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/yaml_serializer.rb
   98 C:/Ruby26-x64/lib/ruby/site_ruby/2.6.0/rubygems/text.rb
   99 C:/Ruby26-x64/lib/ruby/site_ruby/2.6.0/rubygems/user_interaction.rb
  100 C:/Ruby26-x64/lib/ruby/site_ruby/2.6.0/rubygems/ext/builder.rb
  101 C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/feature_flag.rb
  102 C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/source.rb
  103 C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/source/path.rb
  104 C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/source/git.rb
  105 C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/source/rubygems.rb
  106 C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/lockfile_parser.rb
  107 C:/Ruby26-x64/lib/ruby/2.6.0/set.rb
  108 C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/definition.rb
  109 C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/dependency.rb
  110 C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/ruby_dsl.rb
  111 C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/dsl.rb
  112 C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/source_list.rb
  113 C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/source/metadata.rb
  114 C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/lazy_specification.rb
  115 C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/ui.rb
  116 C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/ui/silent.rb
  117 C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/ui/rg_proxy.rb
  118 C:/Ruby26-x64/lib/ruby/2.6.0/tsort.rb
  119 C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/spec_set.rb
  120 C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/vendor/molinillo/lib/molinillo/compatibility.rb
  121 C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/vendor/molinillo/lib/molinillo/gem_metadata.rb
  122 C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/vendor/molinillo/lib/molinillo/delegates/specification_provider.rb
  123 C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/vendor/molinillo/lib/molinillo/errors.rb
  124 C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/vendor/molinillo/lib/molinillo/dependency_graph/action.rb
  125 C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/vendor/molinillo/lib/molinillo/dependency_graph/add_edge_no_circular.rb
  126 C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/vendor/molinillo/lib/molinillo/dependency_graph/add_vertex.rb
  127 C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/vendor/molinillo/lib/molinillo/dependency_graph/delete_edge.rb
  128 C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/vendor/molinillo/lib/molinillo/dependency_graph/detach_vertex_named.rb
  129 C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/vendor/molinillo/lib/molinillo/dependency_graph/set_payload.rb
  130 C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/vendor/molinillo/lib/molinillo/dependency_graph/tag.rb
  131 C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/vendor/molinillo/lib/molinillo/dependency_graph/log.rb
  132 C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/vendor/molinillo/lib/molinillo/dependency_graph/vertex.rb
  133 C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/vendor/molinillo/lib/molinillo/dependency_graph.rb
  134 C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/vendor/molinillo/lib/molinillo/state.rb
  135 C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/vendor/molinillo/lib/molinillo/modules/specification_provider.rb
  136 C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/vendor/molinillo/lib/molinillo/delegates/resolution_state.rb
  137 C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/vendor/molinillo/lib/molinillo/resolution.rb
  138 C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/vendor/molinillo/lib/molinillo/resolver.rb
  139 C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/vendor/molinillo/lib/molinillo/modules/ui.rb
  140 C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/vendor/molinillo/lib/molinillo.rb
  141 C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/vendored_molinillo.rb
  142 C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/resolver/spec_group.rb
  143 C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/resolver.rb
  144 C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/index.rb
  145 C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/source/gemspec.rb
  146 C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/runtime.rb
  147 C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/dep_proxy.rb
  148 C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/remote_specification.rb
  149 C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/stub_specification.rb
  150 C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/endpoint_specification.rb
  151 C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/ruby_version.rb
  152 C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/setup.rb
  153 C:/projects/numo-repro/vendor/bundle/ruby/2.6.0/gems/numo-narray-0.9.1.6/lib/numo/narray.so
  154 C:/projects/numo-repro/vendor/bundle/ruby/2.6.0/gems/numo-narray-0.9.1.6/lib/numo/narray/extra.rb
  155 C:/projects/numo-repro/vendor/bundle/ruby/2.6.0/gems/numo-narray-0.9.1.6/lib/numo/narray.rb
[NOTE]
You may have encountered a bug in the Ruby interpreter or extension libraries.
Bug reports are welcome.
For details: https://www.ruby-lang.org/bugreport.html
```

**Comment by masa16** [comment]
Fixed by https://github.com/ruby-numo/numo-narray/commit/bfd72d5d30dc2fff093c7996ad158bce002419a4
Thank you for your report.

**Comment by ankane** [comment]
Thanks @masa16, that fixed it!
