### ISSUE TITLE
 segmentation fault when nil value NArray calls cast / NMath calls exp. 

### ISSUE THREAD

**Issue by naitoh** [ruby-numo/numo-narray#77]
Hi, Segmentation fault occurs in the following code.

    require 'numo/narray'
    Numo::NArray.cast(nil)

or

    require 'numo/narray'
    Numo::NMath.exp(nil)

Crash Report with Numo::NArray.cast(nil)

```
/Users/naitoh/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/numo-narray-0.9.1.0/lib/numo/narray/extra.rb:159: [BUG] invalid type for md-array: NilClass
ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin16]

-- Crash Report log information --------------------------------------------
   See Crash Report log file under the one of following:                    
     * ~/Library/Logs/DiagnosticReports                                     
     * /Library/Logs/DiagnosticReports                                      
   for more details.                                                        
Don't forget to include the above Crash Report log file in bug reports.     

-- Control frame information -----------------------------------------------
c:0004 p:---- s:0016 e:000015 CFUNC  :array_type
c:0003 p:0034 s:0011 e:000010 METHOD /Users/naitoh/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/numo-narray-0.9.1.0/lib/numo/narray/extra.rb:159
c:0002 p:0024 s:0006 e:000005 EVAL   test10.rb:2 [FINISH]
c:0001 p:0000 s:0003 E:001ef0 (none) [FINISH]

-- Ruby level backtrace information ----------------------------------------
test10.rb:2:in `<main>'
/Users/naitoh/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/numo-narray-0.9.1.0/lib/numo/narray/extra.rb:159:in `cast'
/Users/naitoh/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/numo-narray-0.9.1.0/lib/numo/narray/extra.rb:159:in `array_type'

-- C level backtrace information -------------------------------------------
0   ruby                                0x000000010dfd34f4 rb_vm_bugreport + 132
1   ruby                                0x000000010de725d6 rb_bug + 470
2   narray.bundle                       0x000000010e25641a na_composition3 + 954
3   narray.bundle                       0x000000010e2566c3 na_s_array_type + 35
4   ruby                                0x000000010dfc7530 vm_call_cfunc + 272
5   ruby                                0x000000010dfb1fa0 vm_exec_core + 11456
6   ruby                                0x000000010dfc22d4 vm_exec + 116
7   ruby                                0x000000010de7b5f8 ruby_exec_internal + 136
8   ruby                                0x000000010de7b516 ruby_run_node + 54
9   ruby                                0x000000010de0e2ff main + 79

-- Other runtime information -----------------------------------------------

* Loaded script: test10.rb

* Loaded features:

    0 enumerator.so
    1 thread.rb
    2 rational.so
    3 complex.so
    4 /Users/naitoh/.rbenv/versions/2.4.1/lib/ruby/2.4.0/x86_64-darwin16/enc/encdb.bundle
    5 /Users/naitoh/.rbenv/versions/2.4.1/lib/ruby/2.4.0/x86_64-darwin16/enc/trans/transdb.bundle
    6 /Users/naitoh/.rbenv/versions/2.4.1/lib/ruby/2.4.0/unicode_normalize.rb
    7 /Users/naitoh/.rbenv/versions/2.4.1/lib/ruby/2.4.0/x86_64-darwin16/rbconfig.rb
    8 /Users/naitoh/.rbenv/versions/2.4.1/lib/ruby/2.4.0/rubygems/compatibility.rb
    9 /Users/naitoh/.rbenv/versions/2.4.1/lib/ruby/2.4.0/rubygems/defaults.rb
   10 /Users/naitoh/.rbenv/versions/2.4.1/lib/ruby/2.4.0/rubygems/deprecate.rb
   11 /Users/naitoh/.rbenv/versions/2.4.1/lib/ruby/2.4.0/rubygems/errors.rb
   12 /Users/naitoh/.rbenv/versions/2.4.1/lib/ruby/2.4.0/rubygems/version.rb
   13 /Users/naitoh/.rbenv/versions/2.4.1/lib/ruby/2.4.0/rubygems/requirement.rb
   14 /Users/naitoh/.rbenv/versions/2.4.1/lib/ruby/2.4.0/rubygems/platform.rb
   15 /Users/naitoh/.rbenv/versions/2.4.1/lib/ruby/2.4.0/rubygems/basic_specification.rb
   16 /Users/naitoh/.rbenv/versions/2.4.1/lib/ruby/2.4.0/rubygems/stub_specification.rb
   17 /Users/naitoh/.rbenv/versions/2.4.1/lib/ruby/2.4.0/rubygems/util/list.rb
   18 /Users/naitoh/.rbenv/versions/2.4.1/lib/ruby/2.4.0/x86_64-darwin16/stringio.bundle
   19 /Users/naitoh/.rbenv/versions/2.4.1/lib/ruby/2.4.0/rubygems/specification.rb
   20 /Users/naitoh/.rbenv/versions/2.4.1/lib/ruby/2.4.0/rubygems/exceptions.rb
   21 /Users/naitoh/.rbenv/versions/2.4.1/lib/ruby/2.4.0/rubygems/dependency.rb
   22 /Users/naitoh/.rbenv/versions/2.4.1/lib/ruby/2.4.0/rubygems/core_ext/kernel_gem.rb
   23 /Users/naitoh/.rbenv/versions/2.4.1/lib/ruby/2.4.0/monitor.rb
   24 /Users/naitoh/.rbenv/versions/2.4.1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb
   25 /Users/naitoh/.rbenv/versions/2.4.1/lib/ruby/2.4.0/rubygems.rb
   26 /Users/naitoh/.rbenv/versions/2.4.1/lib/ruby/2.4.0/rubygems/path_support.rb
   27 /Users/naitoh/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/did_you_mean-1.1.0/lib/did_you_mean/version.rb
   28 /Users/naitoh/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/did_you_mean-1.1.0/lib/did_you_mean/core_ext/name_error.rb
   29 /Users/naitoh/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/did_you_mean-1.1.0/lib/did_you_mean/levenshtein.rb
   30 /Users/naitoh/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/did_you_mean-1.1.0/lib/did_you_mean/jaro_winkler.rb
   31 /Users/naitoh/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/did_you_mean-1.1.0/lib/did_you_mean/spell_checker.rb
   32 /Users/naitoh/.rbenv/versions/2.4.1/lib/ruby/2.4.0/delegate.rb
   33 /Users/naitoh/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/did_you_mean-1.1.0/lib/did_you_mean/spell_checkers/name_error_checkers/class_name_checker.rb
   34 /Users/naitoh/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/did_you_mean-1.1.0/lib/did_you_mean/spell_checkers/name_error_checkers/variable_name_checker.rb
   35 /Users/naitoh/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/did_you_mean-1.1.0/lib/did_you_mean/spell_checkers/name_error_checkers.rb
   36 /Users/naitoh/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/did_you_mean-1.1.0/lib/did_you_mean/spell_checkers/method_name_checker.rb
   37 /Users/naitoh/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/did_you_mean-1.1.0/lib/did_you_mean/spell_checkers/null_checker.rb
   38 /Users/naitoh/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/did_you_mean-1.1.0/lib/did_you_mean/formatter.rb
   39 /Users/naitoh/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/did_you_mean-1.1.0/lib/did_you_mean.rb
   40 /Users/naitoh/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/numo-narray-0.9.1.0/lib/numo/narray.bundle
   41 /Users/naitoh/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/numo-narray-0.9.1.0/lib/numo/narray/extra.rb
   42 /Users/naitoh/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/numo-narray-0.9.1.0/lib/numo/narray.rb

[NOTE]
You may have encountered a bug in the Ruby interpreter or extension libraries.
Bug reports are welcome.
For details: http://www.ruby-lang.org/bugreport.html

[IMPORTANT]
Don't forget to include the Crash Report log file under
DiagnosticReports directory in bug reports.

Abort trap: 6
```

Regards.

**Comment by naitoh** [comment]
```
$ gem list --local numo-narray

*** LOCAL GEMS ***

numo-narray (0.9.1.1)
```

I confirmed.
Thank you bug fix.

```
> require 'numo/narray'
> Numo::NArray.cast(nil)
TypeError: invalid type for NArray: NilClass
	from /Users/naitoh/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/numo-narray-0.9.1.1/lib/numo/narray/extra.rb:159:in `array_type'
	from /Users/naitoh/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/numo-narray-0.9.1.1/lib/numo/narray/extra.rb:159:in `cast'
	from (irb):2
	from /Users/naitoh/.rbenv/versions/2.4.1/bin/irb:11:in `<main>'
> Numo::NMath.exp(nil)
TypeError: invalid type for NArray: NilClass
	from (irb):3:in `method_missing'
	from (irb):3
	from /Users/naitoh/.rbenv/versions/2.4.1/bin/irb:11:in `<main>'
```
